apiVersion: apps/v1
kind: Deployment
metadata:
  name: ""
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx

