apiVersion: v1
kind: Pod
metadata:
  name: probe-test
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: "100m"
        limits:
          memory: "128Mi"

